import { Orbitron, Space_Grotesk, Ruslan_Display } from "next/font/google";
import "./globals.css";



const orbitron = Orbitron({ subsets: ["latin"], weight: "800" });
const space = Space_Grotesk({ subsets: ["latin"], weight: "700" });
const ruslan = Ruslan_Display({ subsets: ["latin"],  weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={space.className}>
      <body >{children}</body>
    </html>
  );
}
